version: "2"
services:
  consul:
    build: consul/
    hostname: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: agent -server -bootstrap-expect 1 -config-dir /consul/conf.d
    volumes:
      - ~/volumes/consul/assets/conf.d:/consul/conf.d
  vault:
    build: vault/
    hostname: vault
    ports:
      - "8200:8200"
    command: server -config=/vault/conf.d/vault.hcl
    depends_on:
      - "consul"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    links:
      - consul:consul
    volumes:
      - ~/volumes/vault/assets/conf.d:/vault/conf.d
